main: io.github.itasli.nodamagenohunger.NoDamageNoHunger
name: NoDamageNoHunger
version: 1.1
description: This plugin cancel damage and hunger if player has the permission !
api-version: 1.18
author: itasli
website: spigotmc.org
permissions:
  NoDamageNoHunger.nodamage:
    description: Take no damage
    default: op
  NoDamageNoHunger.nohunger:
    description: Never go hungry
    default: op